name: gyssys_shop
description: "App de inventario para Gyssys shop"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.5
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.2
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/no-image.jpeg